apiVersion: batch/v1
kind: Job
metadata:
  generateName: "offbench-%{ALGO}-%{USER}-job-"
  labels:
    estimated-running-time: "2h"
spec:
  # time to clear the job after a job is finished (completed / failed)
  ttlSecondsAfterFinished: 172800
  template:
    spec:
      priorityClassName: %{PRIORITY}
      # maximum job runtime in seconds
      activeDeadlineSeconds: 86400
      # time for prestop command execution before a container is killed
      terminationGracePeriodSeconds: 300

      # tolerations:
      # - key: aiops-mig
      #   operator: Exists
      #   effect: NoSchedule

      # nodeSelector:
      #   machine-groups: aiops-mig

      containers:
      - name: "%{USER}-job"
        image: "192.168.0.92:5000/max/mujoco:latest"
        imagePullPolicy: Always
        volumeMounts:
        # name need to match volume name below
        - name: workspace-vol
          mountPath: /workspace
          readOnly: false
        - name: dataset-vol
          mountPath: /datasets
          readOnly: false
        - name: shm
          mountPath: /dev/shm
        command: ["/bin/bash"]
        args: [
          "-c", "pip install sota; cd %{PROJECT_PATH}; %{COMMAND}"
        ]
        # command: ["/bin/sh", "-c", "sleep 86400"]
        env:
        - name: SOTA_API_KEY
          value: %{SOTA_KEY}
        - name: WANDB_API_KEY
          value: %{WB_KEY}
        - name: LD_LIBRARY_PATH
          value: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/root/.mujoco/mujoco200/bin
        resources:
          limits:
            cpu: "%{CPU}"
            nvidia.com/gpu: "%{GPU}"
            memory: "%{MEM}"
          requests:
            cpu: "%{CPU}"
            nvidia.com/gpu: "%{GPU}"
            memory: "%{MEM}"
        lifecycle:
          # tasks to execute before container exits (e.g. save checkpoints into job folder)
          preStop:
            exec:
              # command:  ["/bin/sh", "-c", "./scripts/pre-stop.sh"]
              command: ["/bin/sh","-c","echo prestophook triggered > /job-folder/presstophook"]

      imagePullSecrets:
      - name: gitlab-cr-pull-secret
      restartPolicy: Never
      volumes:
      - name: workspace-vol
        hostPath:
          path: /mnt/home/%{USER}
          type: Directory
      - name: dataset-vol
        hostPath:
          path: /raid/
          type: Directory
      - name: shm
        emptyDir:
          medium: Memory
  backoffLimit: 0
