hyperparameters = {
    'halfcheetah-medium-v2':         {'diff_coef': 0.0, 'gn': 9.0, 'oper': False},
    'hopper-medium-v2':              {'diff_coef': 1.0, 'gn': 9.0, 'oper': False},
    'walker2d-medium-v2':            {'diff_coef': 1.0, 'gn': 1.0, 'oper': False},
    'halfcheetah-medium-replay-v2':  {'diff_coef': 0.0, 'gn': 2.0, 'oper': False},
    'hopper-medium-replay-v2':       {'diff_coef': 1.0, 'gn': 4.0, 'oper': False},
    'walker2d-medium-replay-v2':     {'diff_coef': 1.0, 'gn': 4.0, 'oper': False},
    'halfcheetah-medium-expert-v2':  {'diff_coef': 1.0, 'gn': 7.0, 'oper': False},
    'hopper-medium-expert-v2':       {'diff_coef': 10.0, 'gn': 5.0, 'oper': False},
    'walker2d-medium-expert-v2':     {'diff_coef': 1.0, 'gn': 5.0, 'oper': False},
    'antmaze-umaze-v0':              {'diff_coef': 0.5, 'gn': 2.0, 'oper': False},
    'antmaze-umaze-diverse-v0':      {'diff_coef': 0.5, 'gn': 3.0, 'oper': False},
    'antmaze-medium-play-v0':        {'diff_coef': 0.5, 'gn': 2.0, 'oper': True},
    'antmaze-medium-diverse-v0':     {'diff_coef': 0.5, 'gn': 1.0, 'oper': True},
    'antmaze-large-play-v0':        {'diff_coef': 0.5, 'gn': 10.0, 'oper': True},
    'antmaze-large-diverse-v0':      {'diff_coef': 0.5, 'gn': 7.0, 'oper': True},
    'pen-human-v1':                  {'diff_coef': None, 'gn': 7.0, 'oper': False},
    'pen-cloned-v1':                 {'diff_coef': None, 'gn': 8.0, 'oper': False},
    'kitchen-complete-v0':           {'diff_coef': None, 'gn': 9.0, 'oper': False},
    'kitchen-partial-v0':            {'diff_coef': None, 'gn': 10.0, 'oper': False},
    'kitchen-mixed-v0':              {'diff_coef': None, 'gn': 10.0, 'oper': False},
}